version: '2'
services:

  front-envoy:
    image: linimbus/frontproxy_front-envoy:v1.0
    volumes:
      - ./front-envoy-zipkin.json:/etc/front-envoy.json
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  service1:
    image: linimbus/frontproxy_service1:v1.0
    volumes:
      - ./service1-envoy-zipkin.json:/etc/service-envoy.json
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"

  service2:
    image: linimbus/frontproxy_service2:v1.0
    volumes:
      - ./service2-envoy-zipkin.json:/etc/service-envoy.json
    networks:
      envoymesh:
        aliases:
          - service2
    environment:
      - SERVICE_NAME=2
    expose:
      - "80"

  zipkin:
    image: openzipkin/zipkin
    networks:
      envoymesh:
        aliases:
          - zipkin
    expose:
      - "9411"
    ports:
      - "9411:9411"

  ubuntu:
    image: linimbus/ubuntu-tools
    networks:
      - envoymesh

networks:
  envoymesh: {}
